version: '3.4'
services:
  swoole:
    image: "twosee/swoole-coroutine"
    ports:
    - "9508:9508"
    volumes:
    - "./:/root/src"
    command: "php -S 127.0.0.1:8888 -t ."
  redis:
    image: redis
    ports:
    - "6379:6379"
    sysctls:
      net.core.somaxconn: 65535
    restart: always

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  httpbin:
    image: kennethreitz/httpbin
    restart: always
    ports:
      - 8090:80
